import type { BaseEvent, BaseEventMetadata } from './BaseEvent'

export interface DomainEventMetadata
  extends BaseEventMetadata { }

/**
 * DomainEvent represents an event generated by the domain.
 *
 * To create DomainEvents, use the helper functions:
 * - createDomainEvent()
 *
 * To check if a value is an DomainEvent, use the helper function:
 * - isDomainEvent()
 *
 * These helpers ensure correct typing, structure, and metadata assignment.
 */
export interface DomainEvent<TPayload>
  extends Omit<BaseEvent<TPayload>, 'metadata'> {
  aggregateId: string
  source: 'internal'
  metadata: {
    timestamp: string
  } & Partial<DomainEventMetadata>
}
