export interface DomainEventMetadata {
  correlationId?: string
  causationId?: string
  [key: string]: unknown
}

/**
 * DomainEvent represents an event generated by the domain.
 *
 * To create DomainEvents, use the helper functions:
 * - createDomainEvent()
 *
 * To check if a value is an DomainEvent, use the helper function:
 * - isDomainEvent()
 *
 * These helpers ensure correct typing, structure, and metadata assignment.
 */
export interface DomainEvent<TPayload> {
  id: string
  type: string
  aggregateId: string
  source: 'internal'
  payload: TPayload
  timestamp: string
  metadata: Partial<DomainEventMetadata>
}
