name: On Push trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: validate
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: 📦 Install Dependencies
        run: bun install
      - name: 📏 Lint
        run: bun run lint
      - name: 🧹 Format
        run: bun run fmt
      - name: 🛠️ Typecheck
        run: bun run typecheck
      - name: 📋 Coverage
        run: bun run coverage
